name: build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    uses: charmbracelet/meta/.github/workflows/build.yml@main
    secrets:
      gh_pat: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
